#!/bin/bash
# config for gitclone.sh and gitpush.sh

GIT_ADDR="121.40.91.109"
GIT_PORT="29418"
DEFAULT_USER=liux

DEVELOPERS=(\
    tanp\
    zhangm\
    fancc\
    yangzy\
    lianghj\
    xumq\
    niuhx\
    shangsb\
    mengql\
    liux\
    zhaosx\
    chenhq\
)

function GetReviewerEmail() {
    echo $1"@czfw.cn"
}
